project:
  type: website

website:
  title: "Ashutosh Kadam"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Assignment1.qmd
        text: Assignment 1
      - href: Assignment2.qmd
        text: Assignment 2
      - href: Assignment4.qmd
        text: Assigment 4
      - href: PrepareForClass.qmd
        text: Notes and Reviews

format:
  html:
    theme: darkly
    css: styles.css
    toc: false

editor: visual

