project:
  type: website

website:
  title: "Ashutosh Kadam"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: Assignment1.qmd
        text: Assignment 1

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

